version: 2.1

executors:
  emacs-25:
    docker:
      - image: silex/emacs:25-alpine
  emacs-26:
    docker:
      - image: silex/emacs:26-alpine
  emacs-27:
    docker:
      - image: silex/emacs:27-alpine

jobs:
  test:
    parameters:
      executor:
        type: executor
    executors:
      << parameters.executor >>
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            emacs -batch \
              -l ert \
              -l {{cookiecutter.project_slug}}.el \
              -l test/{{cookiecutter.project_slug}}-test.el \
              -f ert-run-tests-batch-and-exit

workflows:
  test:
    jobs:
      - test
    matrix:
      executor:
        - emacs-25
        - emacs-26
        - emacs-27
